{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0a2794a7-4c13-477c-aaac-1c8bf9c7abae",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import cv2\n",
    "import numpy as np\n",
    "from ultralytics import YOLO\n",
    "\n",
    "# -----------------------------------\n",
    "# Page config\n",
    "# -----------------------------------\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Warehouse Management System\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# -----------------------------------\n",
    "# Load AI model\n",
    "# -----------------------------------\n",
    "\n",
    "model = YOLO(\"models/best.pt\")\n",
    "\n",
    "# -----------------------------------\n",
    "# Header\n",
    "# -----------------------------------\n",
    "\n",
    "st.markdown(\n",
    "\"\"\"\n",
    "<h1 style='text-align:center;color:yellow;'>\n",
    "Warehouse Management System\n",
    "</h1>\n",
    "<h3 style='text-align:center;color:orange;'>\n",
    "Bag Counting Management System\n",
    "</h3>\n",
    "\"\"\",\n",
    "unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "# -----------------------------------\n",
    "# Gate Layout\n",
    "# -----------------------------------\n",
    "\n",
    "gate1, gate2, gate3 = st.columns(3)\n",
    "\n",
    "# -----------------------------------\n",
    "# Video Sources\n",
    "# -----------------------------------\n",
    "\n",
    "video_paths = {\n",
    "    \"gate1\": \"videos/gate1.mp4\",\n",
    "    \"gate2\": \"videos/gate2.mp4\",\n",
    "    \"gate3\": \"videos/gate3.mp4\"\n",
    "}\n",
    "\n",
    "# -----------------------------------\n",
    "# Counters\n",
    "# -----------------------------------\n",
    "\n",
    "bag_in = {\"gate1\":0,\"gate2\":0,\"gate3\":0}\n",
    "bag_out = {\"gate1\":0,\"gate2\":0,\"gate3\":0}\n",
    "\n",
    "# -----------------------------------\n",
    "# Function to run bag counting\n",
    "# -----------------------------------\n",
    "\n",
    "def process_video(video_path, frame_holder, gate):\n",
    "\n",
    "    cap = cv2.VideoCapture(video_path)\n",
    "\n",
    "    previous_positions = {}\n",
    "    counted_ids = set()\n",
    "\n",
    "    while cap.isOpened():\n",
    "\n",
    "        ret, frame = cap.read()\n",
    "        if not ret:\n",
    "            break\n",
    "\n",
    "        frame = cv2.resize(frame,(640,480))\n",
    "        height,width,_ = frame.shape\n",
    "\n",
    "        red_line = width//2\n",
    "\n",
    "        results = model.track(frame, persist=True)\n",
    "\n",
    "        if results[0].boxes.id is not None:\n",
    "\n",
    "            boxes = results[0].boxes.xyxy.cpu().numpy()\n",
    "            ids = results[0].boxes.id.cpu().numpy()\n",
    "\n",
    "            for box,track_id in zip(boxes,ids):\n",
    "\n",
    "                x1,y1,x2,y2 = box\n",
    "                center_x = int((x1+x2)/2)\n",
    "\n",
    "                cv2.rectangle(frame,(int(x1),int(y1)),(int(x2),int(y2)),(0,255,0),2)\n",
    "\n",
    "                if track_id not in previous_positions:\n",
    "                    previous_positions[track_id]=center_x\n",
    "                else:\n",
    "\n",
    "                    prev_x = previous_positions[track_id]\n",
    "\n",
    "                    # Loading (Right → Left)\n",
    "                    if prev_x>red_line and center_x<=red_line and track_id not in counted_ids:\n",
    "\n",
    "                        bag_in[gate]+=1\n",
    "                        counted_ids.add(track_id)\n",
    "\n",
    "                    # Unloading (Left → Right)\n",
    "                    if prev_x<red_line and center_x>=red_line and track_id not in counted_ids:\n",
    "\n",
    "                        bag_out[gate]+=1\n",
    "                        counted_ids.add(track_id)\n",
    "\n",
    "                    previous_positions[track_id]=center_x\n",
    "\n",
    "        cv2.line(frame,(red_line,0),(red_line,height),(0,0,255),3)\n",
    "\n",
    "        frame = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)\n",
    "\n",
    "        frame_holder.image(frame)\n",
    "\n",
    "    cap.release()\n",
    "\n",
    "# -----------------------------------\n",
    "# Gate Panels\n",
    "# -----------------------------------\n",
    "\n",
    "with gate1:\n",
    "\n",
    "    st.subheader(\"Gate Number : 01\")\n",
    "\n",
    "    frame_holder1 = st.empty()\n",
    "\n",
    "    st.markdown(\"**Bags In :** {}\".format(bag_in[\"gate1\"]))\n",
    "    st.markdown(\"**Bags Out :** {}\".format(bag_out[\"gate1\"]))\n",
    "\n",
    "with gate2:\n",
    "\n",
    "    st.subheader(\"Gate Number : 02\")\n",
    "\n",
    "    frame_holder2 = st.empty()\n",
    "\n",
    "    st.markdown(\"**Bags In :** {}\".format(bag_in[\"gate2\"]))\n",
    "    st.markdown(\"**Bags Out :** {}\".format(bag_out[\"gate2\"]))\n",
    "\n",
    "with gate3:\n",
    "\n",
    "    st.subheader(\"Gate Number : 03\")\n",
    "\n",
    "    frame_holder3 = st.empty()\n",
    "\n",
    "    st.markdown(\"**Bags In :** {}\".format(bag_in[\"gate3\"]))\n",
    "    st.markdown(\"**Bags Out :** {}\".format(bag_out[\"gate3\"]))\n",
    "\n",
    "# -----------------------------------\n",
    "# Start processing\n",
    "# -----------------------------------\n",
    "\n",
    "process_video(video_paths[\"gate1\"],frame_holder1,\"gate1\")\n",
    "\n",
    "# -----------------------------------\n",
    "# IoT Monitoring Panel\n",
    "# -----------------------------------\n",
    "\n",
    "st.markdown(\"---\")\n",
    "\n",
    "st.markdown(\n",
    "\"\"\"\n",
    "<h2 style='text-align:center;color:cyan'>\n",
    "IOT Parameters Monitoring\n",
    "</h2>\n",
    "\"\"\",\n",
    "unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "iot1,iot2 = st.columns(2)\n",
    "\n",
    "with iot1:\n",
    "\n",
    "    st.metric(\"Temperature\",\"28 °C\")\n",
    "    st.metric(\"Humidity\",\"62 %\")\n",
    "    st.metric(\"Phosphine Gas Level\",\"Safe\")\n",
    "\n",
    "with iot2:\n",
    "\n",
    "    st.metric(\"Smoke & Fire Status\",\"Normal\")\n",
    "    st.metric(\"Gate Status\",\"Closed\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
